# frozen_string_literal: true

# app/services/ldap_service.rb
#  Example Attributes to update
# dn: uid=jorge@hydraulicsales.com,ou=HSS,ou=SPAMFILTER,o=DKI
# mail: jorge@hydraulicsales.com
# uid: jorge@hydraulicsales.com
# givenName: Jorge
# fullName: Salgueiro
# sn: Salgueiro
# ou: Full
# objectClass: inetOrgPerson
# objectClass: organizationalPerson
# objectClass: Person
# objectClass: Top
# objectClass: ndsLoginProperties
# cn: jorge@hydraulicsales.com
# cn: Spamfilter Full User
# userPassword: Salgueiro

require 'net/ldap'

class LdapService
  attr_reader :error_message

  BASE_CONTEXT = 'ou=SPAMFILTER,o=DKI'.freeze

  # These constants were only used to initialized data
  ACTIVE_CUSTS = %w[BGG HSS SEBCO datakey web-site1 BURBUG].freeze
  ACTIVE_CUST_NAMES = {
    BGG: "Behar, Gutt & Glazer",
    HSS: "Hydraulic Sales & service",
    SEBCO: "Library Sales",
    datakey: "Datakey, Inc.",
    "web-site1": "Website One, Inc."
  }

  def initialize(client_ou = nil)
    # Configure your connection to the OES server here.
    # By initializing this here, we ensure a fresh connection is prepped 
    # whenever the service is called.
    @ldap = Net::LDAP.new(
      host: Rails.application.credentials.ldap_server.host,
      port: 389, # Swap to 636 for LDAPS in production
      auth: {
        method: :simple,
        username: Rails.application.credentials.ldap_server.username,
        password: Rails.application.credentials.ldap_server.password
      }
    )
    @client_ou = client_ou
  end

  def add_record(dn:, attributes:)
    if @ldap.add(dn: dn, attributes: attributes)
      true
    else
      @error_message = @ldap.get_operation_result.message
      false
    end
  end

  def update_record(dn:, operations:)
    # This uses the 'replace' operations generated by LdapRecord#build_update_operations
    # which forces the server to set the attributes exactly to what you provide.
    if @ldap.modify(dn: dn, operations: operations)
      true
    else
      # Capture the specific LDAP error (e.g., insufficient access, schema violation)
      @error_message = @ldap.get_operation_result.message
      Rails.logger.error "LDAP Update Failed for #{dn}: #{@error_message}"
      false
    end
  end

  def update_attribute(dn:, attribute_name:, attribute_value:)
    if @ldap.replace_attribute(dn, attribute_name, attribute_value)
      true
    else
      @error_message = @ldap.get_operation_result.message
      false
    end
  end

  def delete_record(dn:)
    if @ldap.delete(dn: dn)
      true
    else
      @error_message = @ldap.get_operation_result.message
      false
    end
  end


  def destroy_customer_and_users(customer_id)
    # 1. Fetch all users belonging to this specific customer
    child_users = search_by_customer_id(customer_id: customer_id)

    # 2. Cascade Delete: Wipe out every child user first
    if child_users.any?
      child_users.each do |user|
        unless @ldap.delete(dn: user.dn)
          @error_message = "Failed to delete child user #{user.mail}: #{@ldap.get_operation_result.message}"
          return false
        end
      end
    end

    # 3. Construct the exact DN for the customer using your base context
    customer_dn = "ou=#{customer_id},#{BASE_CONTEXT}"

    # 4. Delete the now-empty parent Customer record
    if @ldap.delete(dn: customer_dn)
      true
    else
      @error_message = "Failed to delete Customer: #{@ldap.get_operation_result.message}"
      false
    end
  end

  # READ: Search for multiple user records using a standard LDAP filter string
  def search(filter_string: '(objectClass=inetOrgPerson)', base: BASE_CONTEXT)
    filter = Net::LDAP::Filter.construct(filter_string)
    records = []

    # The search method yields each entry it finds to the block
    @ldap.search(base: base, filter: filter) do |entry|
      records << entry
    end

    if @ldap.get_operation_result.code == 0
      records
    else
      @error_message = @ldap.get_operation_result.message
      nil
    end
  end

  def search_active_customers
    search_customers(status: 'active')
  end

  def search_inactive_customers
    search_customers(status: 'inactive')
  end
  def search_customers(status: 'active')
    # 1. Base objectClass filter
    oc_filter = Net::LDAP::Filter.eq("objectClass", "organizationalUnit")

    # 2. Status filter mapping to the description attribute
    status_filter = Net::LDAP::Filter.eq("description", status)

    records = []
    # 3. Combine with the bitwise AND operator (&)
    @ldap.search(base: BASE_CONTEXT, filter: oc_filter & status_filter) do |entry|
      records << entry
    end

    if @ldap.get_operation_result.code == 0
      records
    else
      @error_message = @ldap.get_operation_result.message
      nil
    end
  end

  def search_by_customer_id(customer_id: nil)
    search(base: "ou=#{customer_id},#{BASE_CONTEXT}")
  end

  # READ: Find a single record by its Common Name (CN) within the base context
  def find_by_cn(cn:)
    filter = Net::LDAP::Filter.eq('cn', cn)
    records = []

    @ldap.search(base: BASE_CONTEXT, filter: filter) do |entry|
      records << entry
    end

    if @ldap.get_operation_result.code == 0
      records.first # Returns the single Net::LDAP::Entry object, or nil if none found
    else
      @error_message = @ldap.get_operation_result.message
      nil
    end
  end

  # READ: Find an exact record using its full Distinguished Name (DN)
  def find_by_dn(dn:)
    records = []
    puts dn
    # To search by an exact DN, we use the DN as the base and restrict the scope
    # to only that specific base object, rather than searching the whole tree.
    @ldap.search(base: dn, scope: Net::LDAP::SearchScope_BaseObject) do |entry|
      records << entry
    end

    if @ldap.get_operation_result.code == 0
      records.first
    else
      @error_message = @ldap.get_operation_result.message
      nil
    end
  end

  #
  # Currently deactivaation and reactivation must be done from the console (or some other LDAP editor)
  #
  def reactivate_customer(customer_id:)
    return unless customer_id
    inactive_custs = search_inactive_customers
    return unless inactive_custs
    cust = inactive_custs.select {|c| c[:ou][0] == customer_id}.first

    if cust
      if update_attribute(dn: cust[:dn], attribute_name: :description, attribute_value: 'active')
        puts "Customer ID: #{customer_id} set to active"
        true
      else
        @error_message
      end
    else
      @error_message = @ldap.get_operation_result.message
      nil
    end
  end

  def deactivate_customer(customer_id:)
    return unless customer_id
    active_custs = search_active_customers
    return unless active_custs
    cust = active_custs.select {|c| c[:ou][0] == customer_id}.first

    if cust
      if update_attribute(dn: cust[:dn], attribute_name: :description, attribute_value: 'inactive')
        puts "Customer ID: #{customer_id} set to #{cust[:description]}"
        true
      else
        @error_message
      end
    else
      @error_message = @ldap.get_operation_result.message
      nil
    end
  end
  # These methods are not to be used after initialization
  def add_full_cust_names

    search_active_customers.each do |cust|
      dn = cust[:dn]
      ou = cust[:ou]
      next if ou.count > 1 # Already has a customer name
      update_attribute(dn: dn, attribute_name: :ou, attribute_value: ou << ACTIVE_CUST_NAMES[ou[0].to_sym])
      puts "dn: #{dn}, ou: #{ou}, Name: #{ACTIVE_CUST_NAMES[ou[0].to_sym]}"
    end
  end

  def set_active_flag

    search_active_customers.each do |cust|
      dn = cust[:dn]
      active = cust[:description]
      next if active[0] == 'active' && active.count == 1
      update_attribute(dn: dn, attribute_name: :description, attribute_value: ['active'])
      puts "dn: #{dn}, Description: #{cust[:description]}"
    end
  end
end
