# frozen_string_literal: true

# app/services/ldap_service.rb
#  Example Attributes to update
# dn: uid=jorge@hydraulicsales.com,ou=HSS,ou=SPAMFILTER,o=DKI
# mail: jorge@hydraulicsales.com
# uid: jorge@hydraulicsales.com
# givenName: Jorge
# fullName: Salgueiro
# sn: Salgueiro
# ou: Full
# objectClass: inetOrgPerson
# objectClass: organizationalPerson
# objectClass: Person
# objectClass: Top
# objectClass: ndsLoginProperties
# cn: jorge@hydraulicsales.com
# cn: Spamfilter Full User
# userPassword: Salgueiro

require 'net/ldap'

class LdapService
  attr_reader :error_message

  BASE_CONTEXT = 'ou=SPAMFILTER,o=DKI'.freeze
  ACTIVE_CUSTS = %w[BGG HSS SEBCO datakey web-site1].freeze
  ACTIVE_CUST_NAMES = {
    BGG: "Behar, Gutt & Glazer",
    HSS: "Hydraulic Sales & service",
    SEBCO: "Library Sales",
    datakey: "Datakey, Inc.",
    "web-site1": "Website One, Inc."
  }

  def initialize(client_ou = nil)
    # Configure your connection to the OES server here.
    # By initializing this here, we ensure a fresh connection is prepped 
    # whenever the service is called.
    @ldap = Net::LDAP.new(
      host: 'mail.datakey.cc',
      port: 389, # Swap to 636 for LDAPS in production
      auth: {
        method: :simple,
        username: 'cn=admin,o=dki',
        password: 'oftheproblem'
      }
    )
    @client_ou = client_ou
  end

  def add_record(dn:, attributes:)
    if @ldap.add(dn: dn, attributes: attributes)
      true
    else
      @error_message = @ldap.get_operation_result.message
      false
    end
  end

  def update_record(dn:, operations:)
    # This uses the 'replace' operations generated by LdapRecord#build_update_operations
    # which forces the server to set the attributes exactly to what you provide.
    if @ldap.modify(dn: dn, operations: operations)
      true
    else
      # Capture the specific LDAP error (e.g., insufficient access, schema violation)
      @error_message = @ldap.get_operation_result.message
      Rails.logger.error "LDAP Update Failed for #{dn}: #{@error_message}"
      false
    end
  end

  def update_attribute(dn:, attribute_name:, attribute_value:)
    if @ldap.replace_attribute(dn, attribute_name, attribute_value)
      true
    else
      @error_message = @ldap.get_operation_result.message
      false
    end
  end

  def delete_record(dn:)
    if @ldap.delete(dn: dn)
      true
    else
      @error_message = @ldap.get_operation_result.message
      false
    end
  end
  # READ: Search for multiple records using a standard LDAP filter string
  def search(filter_string: '(objectClass=inetOrgPerson)')
    filter = Net::LDAP::Filter.construct(filter_string)
    records = []

    # The search method yields each entry it finds to the block
    @ldap.search(base: BASE_CONTEXT, filter: filter) do |entry|
      records << entry
    end

    if @ldap.get_operation_result.code == 0
      records
    else
      @error_message = @ldap.get_operation_result.message
      nil
    end
  end

  def search_all_customers
    ou_records = search(filter_string: '(objectClass=organizationalUnit)')
  end

  def search_active_customers
    # 1. Create the filter for the objectClass
    oc_filter = Net::LDAP::Filter.eq("objectClass", "organizationalUnit")
    # 2. Create an array of filters for the OUs and join them with the OR (|) operator
    ou_filter = ACTIVE_CUSTS.map { |ou| Net::LDAP::Filter.eq("ou", ou) }.inject(:|)

    records = []
    @ldap.search(base: BASE_CONTEXT, filter: oc_filter & ou_filter) do |entry|
      records << entry
    end

    if @ldap.get_operation_result.code == 0
      records
    else
      @error_message = @ldap.get_operation_result.message
      nil
    end
  end
  def search_by_customer

  end

  # READ: Find a single record by its Common Name (CN) within the base context
  def find_by_cn(cn:)
    filter = Net::LDAP::Filter.eq('cn', cn)
    records = []

    @ldap.search(base: BASE_CONTEXT, filter: filter) do |entry|
      records << entry
    end

    if @ldap.get_operation_result.code == 0
      records.first # Returns the single Net::LDAP::Entry object, or nil if none found
    else
      @error_message = @ldap.get_operation_result.message
      nil
    end
  end

  # READ: Find an exact record using its full Distinguished Name (DN)
  def find_by_dn(dn:)
    records = []
    puts dn
    # To search by an exact DN, we use the DN as the base and restrict the scope
    # to only that specific base object, rather than searching the whole tree.
    @ldap.search(base: dn, scope: Net::LDAP::SearchScope_BaseObject) do |entry|
      records << entry
    end

    if @ldap.get_operation_result.code == 0
      records.first
    else
      @error_message = @ldap.get_operation_result.message
      nil
    end
  end

  def add_full_cust_names

    search_active_customers.each do |cust|
      dn = cust[:dn]
      ou = cust[:ou]
      next if ou.count > 1 # Already has a customer name
      update_attribute(dn: dn, attribute_name: :ou, attribute_value: ou << ACTIVE_CUST_NAMES[ou[0].to_sym])
      puts "dn: #{dn}, ou: #{ou}, Name: #{ACTIVE_CUST_NAMES[ou[0].to_sym]}"
    end
  end
end
